version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./neo-pacs.crt:/etc/nginx/cert/cert.crt
      - ./neo-pacs.key:/etc/nginx/cert/cert.key
    ports:
      - 8080:8080
      - 443:443
    networks:
      - pacs-network
  orthanc:
    image: jodogne/orthanc-plugins:1.11.0
    container_name: pacs_server
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
     - "${DICOM_PORT}:4242"
     - 8042:8042
    secrets:
      - orthanc.json
    volumes:
      - $PWD/orthanc-db:/var/lib/orthanc/db/
      - ./neo-pacs.crt:/etc/orthanc/orthanc.crt
      - ./neo-pacs.key:/etc/orthanc/orthanc.key
      - ./trusted.crt:/etc/orthanc/trusted.crt
      - ./scripts/IncomingHttpRequestFilter.lua:/etc/orthanc/lua/IncomingHttpRequestFilter.lua
    networks:
      - pacs-network
secrets:
  orthanc.json:
    file: orthanc.json
# volumes:
#   orthanc-db:
networks:
  pacs-network: